language: python
install:
    - pip install -U tox-travis
    - pip install codecov coverage
script: tox
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: required
    - name: Linting
      python: "3.6"
      script: tox -e linters
after_success:
  - codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: guangtianli
  password:
    secure: Qp77fQn0TtwRjZUFXeelBsdGY8toq+pvZ1ei7UoZ3rOOaWBHa5xTKl0oINhw7m+ry4sqUQCNQvMkk4lDearTX4Usan0OYqtW2HlITGrzlpjpZjj6R5Cr4HpeCqlIGpqrMtKtM3FsOoEOoC6iPH4dPIWVTwYTFBpyYegx7sD5mvPPUubvHGP4WADDfN05ykw5KtoVKtYzFZUrbTiQlXjlCpy2KjSlmFAcA6UqdsDxoaynO0bCdy67dlUfRord0Soz1O9DusP4SQAGQD+A8gi7qj0oJhk2VnLoQ6HTlLh4dj24Ucq02M976vckxbFHv/AYh1Dzsgk5ggaldg2yHofI2nA98xPP9uYNCQAc3eZBA8mfOEU2YRoAkjvaidoj97jM4lSEh/fiH0zLq9ESrkqFg/X/IkwaQrGXq0vkdg/07byycdCx9OQC9MfglVcw2jiF9oMRElpXZqElc6Bond6UMseWQwikxSrXtXKgit28PYebx7iEvtHF7Yd7OUhJ0CouHkT2DF1wDtY3N8ztZ87xYDia7li98hMrazLlUzR4ZZJsrWW2vQh0fGuZKJD0x6wYN/HGpOySxMfGc8a2gfkXH00jzVEEBg2bGtR9g6cl7YDD3BuZAI942Eq/c1IL+aSRHnYnPlfn+K+SM1R2lzm+FP0TjoBXxjqGI9LGnEle/58=
  on:
    tags: true
    repo: GuangTianLi/configalchemy
    python: 3.7
